---
version: '3'

services:
  backend:
    image: sulakass/mystem-backend
    ports:
      - "8080:8080"

  frontend:
    image: sulakass/mystem-frontend
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:8080
    ports:
      - "80:80"
    depends_on:
      - backend
